### ISSUE TITLE
Knife round winner suggestion

### ISSUE THREAD

**Issue by ChocOranger** [shobhit-pathak/MatchZy#18]
Currently, if  both teams have the same number of players and the same HP at the end of a knife round, the winner is randomly chosen.

Rather than have a random winner, make the winner the first team that did damage to the enemy.

**Comment by lugaamn** [comment]
i have 1 question how to use command in conolse?

**Comment by shobhit-pathak** [comment]
Hey @ChocOranger, thanks for the suggestion!
This one is interesting, actually I had referred knife logic from Get5, where in the end, randomly a winner is decided.
I'll check whether we can implement a system to make the first time to do the damage the winner

**Comment by lugaamn** [comment]
Oh thank you and one more question. !forceend or !forcematch and !surrender develop such commands? I think (sv_alltalk 1) command worked in live.cfg but vice versa in warmup.cfg sv_alltalk 0 sv_full_alltalk 0 seems to be. admin reserved slot work? 
It's a very useful plugin, thank you

**Comment by shobhit-pathak** [comment]
Hey!
Yes I have to develop `forceend` or `forcematch`. But there is a command, `.restart` which servers the same purpose as `forceend`.
It will force-end the match, stop demo recording and will start the warmup phase again.

For CFGs, they are configurable and you can modify `live.cfg`, `warmup.cfg` and other CFGs are per your need.

Also, there is no admin reserved slot yet. But generally the servers where we have to play pug/scrim/matches should be of 12-14 slots (minimum) so that there can be 5 players of each team, their coaches and still a slot for admin. Because in matches, we cannot kick a player to make a slot for admin.

**Comment by shobhit-pathak** [comment]
Hey!

Since the existing logic is what faceit follows and get5 also used to follow, we will keep it the same for now.
Thanks!
