### ISSUE TITLE
[REQ] Increase the time to send the message

### ISSUE THREAD

**Issue by crashzk** [shobhit-pathak/MatchZy#5]
It would be interesting to increase the time for sending the message informing whether the player was ready or not.

![image](https://github.com/shobhit-pathak/MatchZy/assets/32937653/fa2dbe10-3290-4a9d-bf8e-f46903c11aeb)

A good time would be every 72 seconds, let's say, or even a way to configure the time ourselves. This way we can avoid this message flood.

**Comment by shobhit-pathak** [comment]
Hey!
I've kept the timer for sending messages to 12 seconds (because each message is kept in chat display for ~13 seconds). So as soon as the previous message disappears, new one will be printed.
But I do understand the concern and requirement here, so making the timer configurable would make a lot of sense!

Thanks for the suggestion, I'll make it configurable in the next update! :D
