### ISSUE TITLE
[REQ] Support for message translation

### ISSUE THREAD

**Issue by crashzk** [shobhit-pathak/MatchZy#61]
CSSharp has implemented the [translation](https://docs.cssharp.dev/examples/WithTranslations.html) feature for plugins, I believe we can now expect a future version with this feature.

**Comment by shobhit-pathak** [comment]
Hey!

Translation would be awesome, but at this point I don't have someone who can help me with translations :P
And I think translation can be picked up a bit later, because if we start supporting translation at this stage, it will slow down the upcoming features as we will have to wait for the translation of the new strings before pushing an update

We can start supporting translation once we've made a decent progress with the plugin where we don't have to make major changes.

Thanks!

**Comment by crashzk** [comment]
Hello, news about this feature? Would it be in the plans to implement in the next releases?

Question of help with translations, I think we can leave the language `English` by default and the community can translate it into their language.

For translations that have not been done, the plugin would use the `English` language by default, as in most plugins.

**Comment by shobhit-pathak** [comment]
Hey @crashzk,

I think translations can now be taken up, I just need to fix a few things which I'll probably do in next few updates
Then we will start working on the translations

Thanks! :D

**Comment by candied-apple** [comment]
I can help with the turkish translation. And i think with the help of AI translators other languages will be easier.

**Comment by Max66888** [comment]
> 嘿！
> 
> 翻译会很棒，但目前我没有人可以帮助我翻译：P 而且我认为翻译可以稍后再进行，因为如果我们在这个阶段开始支持翻译，它会减慢翻译速度即将推出的功能，因为我们在推送更新之前必须等待新字符串的翻译
> 
> 一旦我们在插件方面取得了不错的进展，我们就可以开始支持翻译，而无需进行重大更改。
> 
> 谢谢！

I really hope to help you create a Chinese translation！
Please make sure to contact me when you have established the foundation for translation！
I will make every version of MatchZy
Thanks！

**Comment by shobhit-pathak** [comment]
Hey!

Translations are now available in MatchZy.

Thanks!
