### ISSUE TITLE
[BUG] Placing bot and spawn commands are not working

### ISSUE THREAD

**Issue by Sh1su** [shobhit-pathak/MatchZy#67]
Hello 

First, thank you for this amazing plugin. That's help a lot in our Community.

Following the Problems

first here the setup
-------------------------------------------------------------------------------------------------------
Cs2 install over docker in pterodactyl management system
Docker Image: ghcr.io/1zc/steamrt3-pterodactyl:latest

Meta Version
    Metamod:Source version 2.0.0-dev+1266
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Nov 16 2023 05:35:43
    Built from: https://github.com/alliedmodders/metamod-source/commit/1489f33
    Build ID: 1266:1489f33
    http://www.metamodsource.net/

meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin

css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADED]: "MatchZy" (0.6.0-alpha) by WD- (https://github.com/shobhit-pathak/)
    A plugin for running and managing CS2 practice/pugs/scrims/matches!

-------------------------------------------------------------------------------------------------------

The Problem

After we install MatchZy 
- want spawn bot in current position, but it's not working
- I wanted to make a selected area appear with the command .spawn, but your program told me that the command is !tspawn 1, with an exclamation mark, which does not match the documentation. Additionally, it recognizes the command to move me, but does not take me to the spawn

if is possible that we can fix this.

you can look this my problem in this video https://www.youtube.com/watch?v=matCqKY_PVg

**Comment by shobhit-pathak** [comment]
Hey!

Recent CS2 game update has broken teleport and bot spawn feature of practice mode.

To fix it, you will have to update CSSharp, or download matchzy-with-cssharp release from here (I've updated the release):
https://github.com/shobhit-pathak/MatchZy/releases/latest

Or simply update addons/counterstrikesharp/gamedata/gamedata.json file with this:
https://raw.githubusercontent.com/roflmuffin/CounterStrikeSharp/74fd0e0832dbd8a8a2385bc76f0c5f585196b452/configs/addons/counterstrikesharp/gamedata/gamedata.json

Also, I would suggest you to type these commands in chat instead of game console, as that is also bugged in CS2

Thanks!
