### ISSUE TITLE
[Bug] .rcon command don't work with say bind

### ISSUE THREAD

**Issue by EndzE** [shobhit-pathak/MatchZy#77]
.rcon / !rcon / /rcon - commands don't work normally when you bind them like "bind p say .rcon ...", other commands work as expected. 

Demonstration: https://streamable.com/5xy1iy

**Comment by shobhit-pathak** [comment]
Hey!

This is a bug from CSSharp or Valve and an issue is opened there for the same:
https://github.com/roflmuffin/CounterStrikeSharp/issues/231

It will be automatically resolved here once that issue is fixed.

Basically we are not getting the complete message when using say binds, so we will have to wait for it to get fixed.

Thanks!

**Comment by shobhit-pathak** [comment]
Hey!

For now, you can bind it like this: `bind p css_rcon <your_command>`

Thanks!
