### ISSUE TITLE
No score timeline & lossbonus in TAB + all 24 rounds played

### ISSUE THREAD

**Issue by W8100** [shobhit-pathak/MatchZy#81]
Hi!

It's just me oranybody have  this same issue when in match 5v5 there is no score timeline and not even loss bonus.

Also it would be nice to start 5v5 in the "practise mode" 12 rounds as t & 12 as ct no metzer what score it is.

Thank you.

**Comment by tama2cs** [comment]
Hey,

I am not experiencing the same issues as you are. About the "no score timeline": are you sure you use .start or have all players ready up? If you let the warm up time run out I can see issues arise. So use .start or have all players do .ready.

If you want to play 12 rounds on both sides, regardless of score you need to configure the "Playout" option. 
In order to do this you need to change "matchzy_playout_enabled_default" to true instead of false in csgo/cfg/MatchZy/config.cfg
You can also change it with .playout as admin

Guide by developer: https://shobhit-pathak.github.io/MatchZy/configuration/

Hope this helps!

**Comment by shobhit-pathak** [comment]
Hey!
As @tama2cs had mentioned, there is no timeline issue, so make sure that there is not any problem with your config.
