### ISSUE TITLE
Treat Coach slot as a spectator

### ISSUE THREAD

**Issue by hAckyD** [shobhit-pathak/MatchZy#84]
Hey!

Is it possible to treat the coach as a spectator? So that he does not appear in the team?

It's very confusing that he spawns with the team at the start of the round and is then "killed".

We tried it as Spectator and in the team with .coach t or .coach ct.

Maybe I'm just too stupid :)

I love this plugin by the way, everything works so wonderfully!

Thanks and best regards
Anni

![image](https://github.com/shobhit-pathak/MatchZy/assets/39694719/962060fe-439f-400f-92f5-ec3e9eb64d1d)

**Comment by shobhit-pathak** [comment]
Hey!

Sadly it is not possible to treat coaches as spectators, because CS2 doesn't have a coach slot yet.
So this is a workaround that we are using where treat coach as a player and kill them when the freezetime ends.

Hopefully CS2 introduces the coach slot soon so that we don't have to use this workaround and it can become same as CSGO

Thanks!

**Comment by hAckyD** [comment]
Hey!

Ahhhh, I see. Okay, thanks a lot :)

Anni
